/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca;

import biblioteca.GUI.cliente.Clientes;
import biblioteca.GUI.livro.Livros;
import biblioteca.GUI.movimentacao.Movimentacoes;

/**
 *
 * @author demetrius
 */
public class Biblioteca extends javax.swing.JFrame {

    private final int JANELA_CLIENTES = 1;
    private final int JANELA_LIVROS = 2;
    private final int JANELA_MOVS = 3;
    
    /**
     * Creates new form BibliotecaGUI
     */
    public Biblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJanela = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btnClientes = new javax.swing.JButton();
        btnLivros = new javax.swing.JButton();
        btnMovs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setText("Biblioteca");

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setFocusable(false);
        jToolBar1.setRequestFocusEnabled(false);
        jToolBar1.setVerifyInputWhenFocusTarget(false);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicializaClientes(evt);
            }
        });
        jToolBar1.add(btnClientes);

        btnLivros.setText("Livros");
        btnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicializaLivros(evt);
            }
        });
        jToolBar1.add(btnLivros);

        btnMovs.setText("Movimentações");
        btnMovs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicializaMovs(evt);
            }
        });
        jToolBar1.add(btnMovs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 335, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicializa a tela de Clientes
     * @param evt 
     */
    private void inicializaClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicializaClientes
        inicializaTela(JANELA_CLIENTES);
    }//GEN-LAST:event_inicializaClientes

    /**
     * Inicializa a tela de Livros
     * @param evt 
     */
    private void inicializaLivros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicializaLivros
        inicializaTela(JANELA_LIVROS);
    }//GEN-LAST:event_inicializaLivros

    /**
     * Inicializa a tela de Movimentações
     * @param evt 
     */
    private void inicializaMovs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicializaMovs
        inicializaTela(JANELA_MOVS);
    }//GEN-LAST:event_inicializaMovs

    /**
     * Método auxiliar para instanciar a janela especificada
     * @param janela Código da janela escolhida, conforme constantes definidas
     *               no topo da classe
     */
    private void inicializaTela(int janela){
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            switch( janela ){
                case JANELA_CLIENTES:
                    new Clientes().setVisible(true);
                    break;
                case JANELA_LIVROS:
                    new Livros().setVisible(true);
                    break;
                case JANELA_MOVS:
                    new Movimentacoes().setVisible(true);
                    break;
                    
            }
        });
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Biblioteca().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnLivros;
    private javax.swing.JButton btnMovs;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables
}
