/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca.GUI.cliente;

import biblioteca.DAO.ClienteDAODB;
import biblioteca.modelos.Cliente;
import biblioteca.modelos.ClienteTableModel;
import biblioteca.utilidades.MSG;
import java.util.ArrayList;

/**
 *
 * @author demetrius
 */
public class Clientes extends javax.swing.JFrame {

    private ClienteTableModel ctm = new ClienteTableModel();

    /**
     * Creates new form GUIClientes
     */
    public Clientes() {
        atualizarDados();
        initComponents();
    }

    public final void atualizarDados() {
        ArrayList<Cliente> clientes = new ClienteDAODB().listarTodosClientes();
        ctm.setDados(clientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelListaClientes = new javax.swing.JPanel();
        tabelaClientesContainer = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        painelControlesClientes = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnVerMovs = new javax.swing.JButton();
        tituloJanela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca - Clientes");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarSelecao(evt);
            }
        });

        painelListaClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaClientes.setModel(ctm);
        tabelaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaClientes.setShowVerticalLines(false);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarItem(evt);
            }
        });
        tabelaClientesContainer.setViewportView(tabelaClientes);

        javax.swing.GroupLayout painelListaClientesLayout = new javax.swing.GroupLayout(painelListaClientes);
        painelListaClientes.setLayout(painelListaClientesLayout);
        painelListaClientesLayout.setHorizontalGroup(
            painelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaClientesContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        painelListaClientesLayout.setVerticalGroup(
            painelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaClientesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCliente(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCliente(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCliente(evt);
            }
        });

        btnVerMovs.setText("Visualizar Movimentações");
        btnVerMovs.setEnabled(false);

        javax.swing.GroupLayout painelControlesClientesLayout = new javax.swing.GroupLayout(painelControlesClientes);
        painelControlesClientes.setLayout(painelControlesClientesLayout);
        painelControlesClientesLayout.setHorizontalGroup(
            painelControlesClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelControlesClientesLayout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerMovs))
        );
        painelControlesClientesLayout.setVerticalGroup(
            painelControlesClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlesClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelControlesClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(btnNovo)
                    .addComponent(btnVerMovs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloJanela.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelControlesClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJanela, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelControlesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * "Exclui" o cliente selecionado na base
     *
     * @param evt
     */
    private void excluirCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCliente

        ClienteDAODB db = new ClienteDAODB();
        Cliente cliente = ctm.getCliente(tabelaClientes.getSelectedRow());

        if (MSG.confirm(this, "Deseja realmente excluir o cliente selecionado?")) {

            if (db.deletar(cliente.getId())) {

                MSG.show(this, "Cliente excluido com sucesso!");
                atualizarDados();

            } else {

                MSG.show(this, "Falha na exclusão do cliente.");

            }

        }

    }//GEN-LAST:event_excluirCliente

    /**
     * Disparado quando o usuário seleciona um item na tabela
     *
     * @param evt O Evento gerado.
     */
    private void selecionarItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarItem
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnVerMovs.setEnabled(true);
    }//GEN-LAST:event_selecionarItem

    /**
     * Disparado quando o usuário clica fora da tabela
     *
     * @param evt O Evento gerado.
     */
    private void cancelarSelecao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarSelecao
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnVerMovs.setEnabled(false);
        tabelaClientes.clearSelection();
    }//GEN-LAST:event_cancelarSelecao

    /**
     * Inicializa a interface para editar um cliente
     *
     * @param evt
     */
    private void editarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCliente
        Cliente cliente = ctm.getCliente(tabelaClientes.getSelectedRow());
        java.awt.EventQueue.invokeLater(() -> {
            new AlterarCliente(cliente, this).setVisible(true);
        });
    }//GEN-LAST:event_editarCliente

    /**
     * Inicializa a interface para cadastrar um cliente
     *
     * @param evt
     */
    private void cadastrarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCliente
        java.awt.EventQueue.invokeLater(() -> {
            new CadastrarCliente(this).setVisible(true);
        });
    }//GEN-LAST:event_cadastrarCliente

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Clientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVerMovs;
    private javax.swing.JPanel painelControlesClientes;
    private javax.swing.JPanel painelListaClientes;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JScrollPane tabelaClientesContainer;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables
}
