/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca.GUI.livro;

import biblioteca.DAO.LivroDAODB;
import biblioteca.modelos.Livro;
import biblioteca.utilidades.MSG;

/**
 * Interface para atualização dos dados de um livro na base de dados.
 *
 * @author demetrius
 */
public class AlterarLivro extends javax.swing.JFrame {

    private LivroDAODB db = new LivroDAODB();
    private Livro livro;
    private Livros parent;

    /**
     * Creates new form AlterarLivro
     *
     * @param livro O livro a ser alterado
     * @param parent A janela "pai" desta (Livros - tela principal), para
     * atualização da tabela de livros
     */
    public AlterarLivro(Livro livro, Livros parent) {
        this.livro = livro;
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJanela = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        txtISBN = new javax.swing.JTextField();
        labelISBN = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        labelAutores = new javax.swing.JLabel();
        txtAutores = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        labelEditora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloJanela.setText("Alterar Livro");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharJanela(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarLivro(evt);
            }
        });

        txtISBN.setText(livro.getISBN()
        );

        labelISBN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelISBN.setText("ISBN");

        labelAno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAno.setText("Ano de Publicação");

        txtAno.setText(String.valueOf(livro.getAnoPublicacao()));

        txtNome.setText(livro.getNome());

        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitulo.setText("Título");

        labelAutores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAutores.setText("Autor(es)");

        txtAutores.setText(livro.getAutores());

        txtEditora.setText(livro.getEditora());

        labelEditora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEditora.setText("Editora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnOK)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(labelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtEditora)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOK))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Valida os dados e atualiza o livro na base
     *
     * @param evt
     */
    private void atualizarLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarLivro

        int ano;

        try {
            
            // Se txtAno não contiver um valor válido, a excecução deste método
            // é cancelada (catch NumberFormatException)
            ano = Integer.parseInt(txtAno.getText());

            // Campos vazios
            if (txtISBN.getText().isEmpty() || txtAutores.getText().isEmpty()
                    || txtEditora.getText().isEmpty() || txtISBN.getText().isEmpty() || txtAno.getText().isEmpty()) {

                MSG.show(this, "Nenhum campo pode ficar vazio!");

            // Validar novo ISBN, se for diferente do atual
            } else if (!(txtISBN.getText().equals(livro.getISBN())) && db.verificarISBN(txtISBN.getText())) {

                MSG.show(this, "ISBN informado já existe!");

            // Nenhuma alteração nos dados
            } else if (txtNome.getText().equals(livro.getNome())
                    && txtAutores.getText().equals(livro.getAutores())
                    && txtEditora.getText().equals(livro.getEditora())
                    && txtISBN.getText().equals(livro.getISBN())
                    && ano == livro.getAnoPublicacao()) {

                MSG.show(this, "Nenhuma alteração efetuada.");

                // Tudo OK
            } else {
                
                livro.setISBN(txtISBN.getText().trim());
                livro.setNome(txtNome.getText().trim());
                livro.setAutores(txtAutores.getText().trim());
                livro.setEditora(txtEditora.getText().trim());
                livro.setAnoPublicacao(ano);

                if (db.atualizar(livro)) {

                    MSG.show(this, "Livro atualizado com sucesso!");
                    parent.atualizarDados();
                    this.dispose();

                } else {

                    MSG.show(this, "Falha na atualização do livro");

                }

            }

        } catch (NumberFormatException e) {
            MSG.show(this, "Ano deve conter um valor numérico!");
        }

    }//GEN-LAST:event_atualizarLivro

    /**
     * Auto-explicativo
     *
     * @param evt
     */
    private void fecharJanela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharJanela
        this.dispose();
    }//GEN-LAST:event_fecharJanela

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelAutores;
    private javax.swing.JLabel labelEditora;
    private javax.swing.JLabel labelISBN;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel tituloJanela;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAutores;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
