/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca.GUI.livro;

import biblioteca.modelos.Livro;

/**
 *
 * @author demetrius
 */
public class DetalhesLivro extends javax.swing.JFrame {

    private final Livro livro;

    /**
     * Creates new form DetalhesLivro
     * @param livro
     */
    public DetalhesLivro(Livro livro) {
        this.livro = livro;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJanela = new javax.swing.JLabel();
        labelTxtTitulo = new javax.swing.JLabel();
        labelTxtDisp = new javax.swing.JLabel();
        labelTxtAutores = new javax.swing.JLabel();
        labelTxtISBN = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelAutores = new javax.swing.JLabel();
        labelISBN = new javax.swing.JLabel();
        labelDisp = new javax.swing.JLabel();
        labelTxtEditora = new javax.swing.JLabel();
        labelEditora = new javax.swing.JLabel();
        labelTxtAno = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloJanela.setText("Livro Nª " + livro.getId());

        labelTxtTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtTitulo.setText("Título: ");

        labelTxtDisp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtDisp.setText("Disponível:");

        labelTxtAutores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtAutores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtAutores.setText("Autore(s):");

        labelTxtISBN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtISBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtISBN.setText("ISBN: ");

        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTitulo.setText(livro.getNome());

        labelAutores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAutores.setText(livro.getAutores());

        labelISBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelISBN.setText(livro.getISBN());

        labelDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDisp.setText(livro.isDisponivel() ? "Sim" : "Não");

        labelTxtEditora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtEditora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtEditora.setText("Editora:");

        labelEditora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEditora.setText(livro.getEditora());

        labelTxtAno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtAno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtAno.setText("Ano de Publicação");

        labelAno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAno.setText(String.valueOf(livro.getAnoPublicacao())
        );

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharJanela(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTxtAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTxtTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTxtISBN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelISBN)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelTxtDisp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTxtEditora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(63, 63, 63)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tituloJanela)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTxtAutores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelISBN)
                        .addComponent(labelTxtISBN)
                        .addComponent(labelTxtDisp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtTitulo)
                    .addComponent(labelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTxtAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtEditora)
                    .addComponent(labelEditora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtAno)
                    .addComponent(labelAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharJanela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharJanela
        this.dispose();
    }//GEN-LAST:event_fecharJanela

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelAutores;
    private javax.swing.JLabel labelDisp;
    private javax.swing.JLabel labelEditora;
    private javax.swing.JLabel labelISBN;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTxtAno;
    private javax.swing.JLabel labelTxtAutores;
    private javax.swing.JLabel labelTxtDisp;
    private javax.swing.JLabel labelTxtEditora;
    private javax.swing.JLabel labelTxtISBN;
    private javax.swing.JLabel labelTxtTitulo;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables
}
