/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca.GUI.livro;

import biblioteca.Biblioteca;
import biblioteca.DAO.LivroDAODB;
import biblioteca.modelos.Livro;
import biblioteca.modelos.LivroTableModel;
import biblioteca.utilidades.MSG;
import java.util.ArrayList;

/**
 *
 * @author demetrius
 */
public class Livros extends javax.swing.JFrame {

    private LivroTableModel ltm = new LivroTableModel();

    /**
     * Creates new form Livros
     */
    public Livros() {
        atualizarDados();
        initComponents();
        redimensionaLarguraColunas();
    }

    /**
     * Auto-Explicativo
     */
    public final void redimensionaLarguraColunas() {
        tabelaLivros.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabelaLivros.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabelaLivros.getColumnModel().getColumn(2).setPreferredWidth(294);
        tabelaLivros.getColumnModel().getColumn(3).setPreferredWidth(70);
    }

    /**
     * Preenche (ou atualiza) a tabela de Livros com os dados da base
     */
    public final void atualizarDados() {
        ArrayList<Livro> dados = new LivroDAODB().listarTodosLivros();
        ltm.setDados(dados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJanela = new javax.swing.JLabel();
        painelLista = new javax.swing.JPanel();
        tabelaLivrosContainer = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        painelControles = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarSelecao(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                menuPrincipal(evt);
            }
        });

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloJanela.setText("Livros");

        tabelaLivros.setModel(ltm);
        tabelaLivros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaLivros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarItem(evt);
            }
        });
        tabelaLivrosContainer.setViewportView(tabelaLivros);

        javax.swing.GroupLayout painelListaLayout = new javax.swing.GroupLayout(painelLista);
        painelLista.setLayout(painelListaLayout);
        painelListaLayout.setHorizontalGroup(
            painelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaLivrosContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        painelListaLayout.setVerticalGroup(
            painelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaLivrosContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuPrincipal(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirLivro(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarLivro(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLivro(evt);
            }
        });

        btnDetalhes.setText("Detalhes");
        btnDetalhes.setEnabled(false);
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalhesLivro(evt);
            }
        });

        javax.swing.GroupLayout painelControlesLayout = new javax.swing.GroupLayout(painelControles);
        painelControles.setLayout(painelControlesLayout);
        painelControlesLayout.setHorizontalGroup(
            painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlesLayout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalhes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir))
        );
        painelControlesLayout.setVerticalGroup(
            painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(btnNovo)
                    .addComponent(btnDetalhes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Disparado quando o usuário fecha a janela ou clica em "Voltar"
     * @param evt
     */
    private void menuPrincipal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_menuPrincipal
        java.awt.EventQueue.invokeLater(() -> {
            new Biblioteca().setVisible(true);
        });
    }//GEN-LAST:event_menuPrincipal

    /**
     * Fecha a janela, causando o disparo do método "menuPrincipal"
     * @param evt
     */
    private void voltarMenuPrincipal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuPrincipal
        this.dispose();
    }//GEN-LAST:event_voltarMenuPrincipal

    /**
     * Inicializa a interface para cadastro de um novo livro
     * @param evt 
     */
    private void cadastrarLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLivro
        java.awt.EventQueue.invokeLater(() -> {
            new CadastrarLivro(this).setVisible(true);
        });
    }//GEN-LAST:event_cadastrarLivro

    /**
     * Disparado quando o usuário clica fora da tabela
     * @param evt O Evento gerado.
     */
    private void cancelarSelecao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarSelecao
        btnDetalhes.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        tabelaLivros.clearSelection();
    }//GEN-LAST:event_cancelarSelecao

    /**
     * Disparado quando o usuário seleciona um item na tabela
     * @param evt O Evento gerado.
     */
    private void selecionarItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarItem
        btnDetalhes.setEnabled(true);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_selecionarItem

    /**
     * Inicializa a interface para editar um livro
     * @param evt
     */
    private void editarLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLivro
        Livro livro = ltm.getLivro(tabelaLivros.getSelectedRow());
        java.awt.EventQueue.invokeLater(() -> {
            new AlterarLivro(livro, this).setVisible(true);
        });
    }//GEN-LAST:event_editarLivro

    /**
     * "Exclui" o livro selecionado na base
     * @param evt
     */
    private void excluirLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirLivro
        LivroDAODB db = new LivroDAODB();
        Livro livro = ltm.getLivro(tabelaLivros.getSelectedRow());

        if (MSG.confirm(this, "Deseja realmente excluir?")) {

            if (db.deletar(livro.getId())) {

                MSG.show(this, "Livro excluido com sucesso!");
                atualizarDados();

            } else {

                MSG.show(this, "Falha na exclusão do livro.");

            }

        }
    }//GEN-LAST:event_excluirLivro

    private void detalhesLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalhesLivro
        Livro livro = ltm.getLivro(tabelaLivros.getSelectedRow());
        java.awt.EventQueue.invokeLater(() -> {
            new DetalhesLivro(livro).setVisible(true);
        });
    }//GEN-LAST:event_detalhesLivro

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel painelControles;
    private javax.swing.JPanel painelLista;
    private javax.swing.JTable tabelaLivros;
    private javax.swing.JScrollPane tabelaLivrosContainer;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables

}
