/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca.GUI.movimentacao;

import biblioteca.DAO.MovLivroDAODB;
import biblioteca.modelos.MovLivro;
import biblioteca.modelos.MovLivroTableModel;
import biblioteca.modelos.Movimentacao;
import biblioteca.utilidades.MSG;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author demetrius
 */
public class DetalhesMovimentacao extends javax.swing.JFrame {
    
    Movimentacoes parent;
    Movimentacao movimentacao;
    MovLivroTableModel mltm;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/uuuu");
    MovLivroDAODB movLivroDB = new MovLivroDAODB();

    /**
     * Creates new form DetalhesMovimentacao
     * @param movimentacao
     * @param parent
     */
    public DetalhesMovimentacao(Movimentacao movimentacao, Movimentacoes parent) {
        this.parent = parent;
        this.movimentacao = movimentacao;
        mltm = new MovLivroTableModel(movimentacao.getDataPrevistaDevolucao());
        mltm.setDados(movimentacao.getMovLivros());
        initComponents();
        redimensionaLarguraColunas();
    }
    
    
    private void redimensionaLarguraColunas() {
        tabelaMovs.getColumnModel().getColumn(0).setPreferredWidth(300);
        tabelaMovs.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabelaMovs.getColumnModel().getColumn(2).setPreferredWidth(80);
    }
    
    public void atualizarListaMovLivros(){
        
        // Recarrega da base a lista de livros da mov. atual
        ArrayList<MovLivro> movLivros = movLivroDB.listarPorMovimentacao(movimentacao.getId());
        
        // Passa para o objeto de mov. a nova lista de livros
        movimentacao.setMovLivros(movLivros);
        
        // Atualiza a tabela de livros
        mltm.setDados(movLivros);
        
        // Atualiza o texto da label de status
        labelStatus.setText(setStatusTxt());
        
        // Atualiza, na tela principal a tabela de movs., para que já contenha os dados atualizados
        parent.atualizarDados();
        
    }
    
    public String setStatusTxt(){
        return movimentacao.verificarTodosDevolvidos() ? "Concluída" : "Pendente";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJanela = new javax.swing.JLabel();
        labelTxtCliente = new javax.swing.JLabel();
        labelTxtStatus = new javax.swing.JLabel();
        labelTxtDataRetirada = new javax.swing.JLabel();
        labelTxtDevPrev = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelDataRetirada = new javax.swing.JLabel();
        labelDevPrev = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelTxtDataRetirada1 = new javax.swing.JLabel();
        painelLista = new javax.swing.JPanel();
        tabelaContainer = new javax.swing.JScrollPane();
        tabelaMovs = new javax.swing.JTable();
        painelControles = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnDevolverPendentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarSelecao(evt);
            }
        });

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloJanela.setText("Movimentação Nº " + movimentacao.getId());

        labelTxtCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtCliente.setText("Cliente: ");

        labelTxtStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtStatus.setText("Status:");

        labelTxtDataRetirada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtDataRetirada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtDataRetirada.setText("Data de Retirada:");

        labelTxtDevPrev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTxtDevPrev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtDevPrev.setText("Devolução Prevista: ");

        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCliente.setText(movimentacao.getCliente().getId() + " - " + movimentacao.getCliente().getNome());

        labelDataRetirada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDataRetirada.setText(movimentacao.getDataRetirada().format(dtf));

        labelDevPrev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDevPrev.setText(movimentacao.getDataPrevistaDevolucao().format(dtf));

        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelStatus.setText(setStatusTxt());

        labelTxtDataRetirada1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTxtDataRetirada1.setText("Livros:");

        tabelaMovs.setModel(mltm);
        tabelaMovs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaMovs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarItem(evt);
            }
        });
        tabelaContainer.setViewportView(tabelaMovs);

        javax.swing.GroupLayout painelListaLayout = new javax.swing.GroupLayout(painelLista);
        painelLista.setLayout(painelListaLayout);
        painelListaLayout.setHorizontalGroup(
            painelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaContainer)
        );
        painelListaLayout.setVerticalGroup(
            painelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharJanela(evt);
            }
        });

        btnDevolver.setText("Devolver");
        btnDevolver.setEnabled(false);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverLivro(evt);
            }
        });

        btnDevolverPendentes.setText("Devolver Todos os Pendentes");
        btnDevolverPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverTodosPendentes(evt);
            }
        });

        javax.swing.GroupLayout painelControlesLayout = new javax.swing.GroupLayout(painelControles);
        painelControles.setLayout(painelControlesLayout);
        painelControlesLayout.setHorizontalGroup(
            painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlesLayout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDevolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolverPendentes))
        );
        painelControlesLayout.setVerticalGroup(
            painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelControlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnDevolver)
                    .addComponent(btnDevolverPendentes))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTxtDataRetirada1)
                            .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTxtDataRetirada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTxtCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTxtStatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTxtDevPrev)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDevPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTxtDevPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDevPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTxtDataRetirada1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharJanela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharJanela
        this.dispose();
    }//GEN-LAST:event_fecharJanela

    private void cancelarSelecao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarSelecao
        btnDevolver.setEnabled(false);
        tabelaMovs.clearSelection();
    }//GEN-LAST:event_cancelarSelecao

    private void selecionarItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarItem
        if(!mltm.getMovLivro(tabelaMovs.getSelectedRow()).isDevolvido())
            btnDevolver.setEnabled(true);
    }//GEN-LAST:event_selecionarItem

    private void devolverLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLivro
        
        MovLivro movLivro = mltm.getMovLivro(tabelaMovs.getSelectedRow());
        
        /*Console.println("idMovLivro: " + movLivro.getId() + "\n"
        + "idMovimentacao: " + movLivro.getIdMovimentacao() + "\n"
        + "idLivro: " + movLivro.getLivro().getId());*/
        
        if(!movLivroDB.devolver(movLivro)){
        
            MSG.show(this, "Erro na devolução do Livro.");
        
        } else {
        
            MSG.show(this, "Livro devolvido com sucesso!");
            atualizarListaMovLivros();
        
        }
        
    }//GEN-LAST:event_devolverLivro

    private void devolverTodosPendentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverTodosPendentes
        
        ArrayList<MovLivro> pendentes = mltm.getPendentes();
        
        String out = "Falha na devolução dos seguintes livros:\n";
        boolean teste = true;
        
        for( MovLivro ml : pendentes ){
            
            if(!movLivroDB.devolver(ml)){
        
                out += ml.getLivro().getISBN() + " - " + ml.getLivro().getNome();
                teste = false;

            }
            
        }
        
        if(teste){
            out = "Todos os livros devolvidos com sucesso!";            
        }
        
        MSG.show(this, out);
        
        atualizarListaMovLivros();
        
    }//GEN-LAST:event_devolverTodosPendentes


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnDevolverPendentes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelDataRetirada;
    private javax.swing.JLabel labelDevPrev;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTxtCliente;
    private javax.swing.JLabel labelTxtDataRetirada;
    private javax.swing.JLabel labelTxtDataRetirada1;
    private javax.swing.JLabel labelTxtDevPrev;
    private javax.swing.JLabel labelTxtStatus;
    private javax.swing.JPanel painelControles;
    private javax.swing.JPanel painelLista;
    private javax.swing.JScrollPane tabelaContainer;
    private javax.swing.JTable tabelaMovs;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables

}
