/**
 * Biblioteca - Sistema de Movimentação de Livros
 *
 * Demétrius Jr. (github.com/15demi08)
 *
 */
package biblioteca.GUI.movimentacao;

import biblioteca.Biblioteca;
import biblioteca.DAO.MovimentacaoDAODB;
import biblioteca.GUI.movimentacao.fluxoRetirada.NovaRetirada;
import biblioteca.modelos.Movimentacao;
import biblioteca.modelos.MovimentacaoTableModel;
import java.util.ArrayList;

/**
 *
 * @author demetrius
 */
public class Movimentacoes extends javax.swing.JFrame {
    
    MovimentacaoTableModel mtm = new MovimentacaoTableModel();

    /**
     * Creates new form Movimentacoes
     */
    public Movimentacoes() {
        atualizarDados();
        initComponents();
        redimensionaLarguraColunas();
    }
    
    public final void atualizarDados(){
        ArrayList<Movimentacao> movs = new MovimentacaoDAODB().listarTodasMovs();
        mtm.setDados(movs);
    }
    
    private void redimensionaLarguraColunas(){
        tabelaMovimentacoes.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabelaMovimentacoes.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabelaMovimentacoes.getColumnModel().getColumn(2).setPreferredWidth(40);
        tabelaMovimentacoes.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelaMovimentacoes.getColumnModel().getColumn(4).setPreferredWidth(110);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJanela = new javax.swing.JLabel();
        painelLista = new javax.swing.JPanel();
        tabelaMovimentacoesContainer = new javax.swing.JScrollPane();
        tabelaMovimentacoes = new javax.swing.JTable();
        painelControles = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        btnNova = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarSelecao(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                menuPrincipal(evt);
            }
        });

        tituloJanela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloJanela.setText("Movimentações");

        tabelaMovimentacoes.setModel(mtm);
        tabelaMovimentacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarItem(evt);
            }
        });
        tabelaMovimentacoesContainer.setViewportView(tabelaMovimentacoes);

        javax.swing.GroupLayout painelListaLayout = new javax.swing.GroupLayout(painelLista);
        painelLista.setLayout(painelListaLayout);
        painelListaLayout.setHorizontalGroup(
            painelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaMovimentacoesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        painelListaLayout.setVerticalGroup(
            painelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaMovimentacoesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuPrincipal(evt);
            }
        });

        btnDetalhes.setText("Detalhes");
        btnDetalhes.setEnabled(false);
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalhesMovimentacao(evt);
            }
        });

        btnNova.setText("Nova");
        btnNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaMovimentacao(evt);
            }
        });

        javax.swing.GroupLayout painelControlesLayout = new javax.swing.GroupLayout(painelControles);
        painelControles.setLayout(painelControlesLayout);
        painelControlesLayout.setHorizontalGroup(
            painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlesLayout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalhes))
        );
        painelControlesLayout.setVerticalGroup(
            painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnDetalhes)
                    .addComponent(btnNova))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelControles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPrincipal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_menuPrincipal
        java.awt.EventQueue.invokeLater(() -> {
            new Biblioteca().setVisible(true);
        });
    }//GEN-LAST:event_menuPrincipal

    private void voltarMenuPrincipal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuPrincipal
        this.dispose();
    }//GEN-LAST:event_voltarMenuPrincipal

    private void novaMovimentacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaMovimentacao
        java.awt.EventQueue.invokeLater(() -> {
            new NovaRetirada().setVisible(true);
        });
    }//GEN-LAST:event_novaMovimentacao

    private void detalhesMovimentacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalhesMovimentacao
        Movimentacao movimentacao = mtm.getMovimentacao(tabelaMovimentacoes.getSelectedRow());
        java.awt.EventQueue.invokeLater(() -> {
            new DetalhesMovimentacao(movimentacao, this).setVisible(true);
        });
    }//GEN-LAST:event_detalhesMovimentacao

    private void cancelarSelecao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarSelecao
        btnDetalhes.setEnabled(false);
        tabelaMovimentacoes.clearSelection();
    }//GEN-LAST:event_cancelarSelecao

    private void selecionarItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarItem
        btnDetalhes.setEnabled(true);
    }//GEN-LAST:event_selecionarItem


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnNova;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel painelControles;
    private javax.swing.JPanel painelLista;
    private javax.swing.JTable tabelaMovimentacoes;
    private javax.swing.JScrollPane tabelaMovimentacoesContainer;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables
}
